### ISSUE TITLE
OAuth2 POST request failing

### ISSUE THREAD

**Issue by ivov** [MLH-Fellowship/n8n#23]
**Describe the bug**
The OAuth2 flow is failing to send out the POST request. This is happening with the Instagram node OAuth2 currently in development and used to happen with the Spotify node OAuth2. (It is still unclear why it resolved itself with the Spotify node.)

[Facebook's token reference](https://developers.facebook.com/docs/instagram-basic-display-api/guides/getting-access-tokens-and-permissions)

**To Reproduce**
1. Get the [Instagram branch](https://github.com/MLH-Fellowship/n8n/tree/instagram-basic-display-node)
2. Make an [Instagram app](https://developers.facebook.com/apps/)
3. Start the node with tunneling: `./packages/cli/bin/n8n start --tunnel`
4. Create an Instagram credential, filling in Client ID and Client Secret from step 2.
5. Try to connect. An Instagram popup screen will appear. Press `Continue`.

**Expected behavior**
The popup screen redirects to the callback URL, which correctly contains a `code=...`. So far, so good. This `code` must be used in the next step in the OAuth2 flow, namely the POST request to `https://api.instagram.com/oauth/access_token`. **However, that POST request is not sent.** The popup screen remains blank showing the callback URL, loading for 30 seconds until it shows a `504 Gateway Time-out` error. The console then shows an `[ERR_HTTP2_GOAWAY_SESSION]` error.

![](https://cdn.discordapp.com/attachments/719636584047312906/723299236581736521/code.png)
![](https://cdn.discordapp.com/attachments/719636584047312906/723299222178365501/goaway.png)

A snapshot of the credentials as read inside `oAuthCredentialAuthorize()` in `CredentialsInput.vue`, right after clicking `Connect`:

![Untitled](https://user-images.githubusercontent.com/44588767/85172942-86f7d600-b248-11ea-9373-9c0d997eaaa0.png)

**Environment (please complete the following information):**
- OS: Windows 8.1
- n8n Version: 0.69.0
- Node.js Version: 12.18.0

**Additional context**
What I've tried:
- Changing the requested scopes.
- Changing the `authQueryParameters` from `default: response_type=code`  to `default:''`.
- Adding `authQueryParameters` with `default: 'grant_type=authorization_code'`
- Testing on a different browser, same result.
- Trying to create the credential using the cloud URL instead of localhost, same result.
- Making a curl POST request with my credentials, as in example below. The curl POST request succeeds.

```bash
curl -X POST \
  https://api.instagram.com/oauth/access_token \
  -F client_id=990602627938098 \
  -F client_secret=eb8c7... \
  -F grant_type=authorization_code \
  -F redirect_uri=https://socialsizzle.herokuapp.com/auth/ \
  -F code=AQBx-hBsH3...
```

What I'm trying:
- Looking into the `this.helpers.requestOAuth2` [function](https://github.com/MLH-Fellowship/n8n/blob/d9906e1b24989db2c200f38542127cc98846ab0a/packages/core/src/NodeExecuteFunctions.ts#L124) to see if/how to debug it. This is slow-going because the tunneling script has a bug which does not allow for `ctrl+c` to stop the process in Windows, so it is necessary to close the terminal and manually identify the process with `netstat -ano | findstr "PID :5678"` and end it with `tskill [number]` in order to release port `5678`. If the port is not released, tunneling creates a different cloud URL.

**Comment by RicardoE105** [comment]
@ivov Not sure how you are testing this if the node does not have credentials? Maybe you did not push the lastest changes? If so please do so that I can review it. Thanks

**Comment by ivov** [comment]
Hey @RicardoE105, thanks a lot for looking into this!

Yes, the credentials are [here](https://github.com/MLH-Fellowship/n8n/blob/instagram-basic-display-node/packages/nodes-base/credentials/InstagramBasicDisplayApi.credentials.ts).

The branch is the one linked in the issue, [this one](https://github.com/MLH-Fellowship/n8n/tree/instagram-basic-display-node).

**Comment by ivov** [comment]
Update on this issue, as it seems to be more general.

**Description**

Some OAuth2 credentials are not connecting. GitHub connects, but Slack, Instagram, and Spotify do not. Specifically, **the OAuth2 POST request step is failing.** Pressing the `Allow` button in the popup screen causes loading for around 30 seconds, and finally `504 Gateway Time-out` is shown in the body of the popup screen, with the console showing `[ERR_HTTP2_GOAWAY_SESSION]`. The popup screen address bar shows the OAuth2 callback URL with the correct `code=...` string.

```
https://sa44gcghnl7czbh8s64ncwh2.hooks.n8n.cloud/rest/oauth2-credential/callback?code=[long string here]&state=[long string here]
```

**To reproduce**
1. Clone and build the latest 0.70.0 release.
2. Run it with localtunnel `./packages/cli/bin/n8n start --tunnel`
3. Make a Slack app and add the n8n callback URI.
4. Make a Slack credential and try to connect.
5. Popup screen appears. Click on `Allow`. The popup screen goes blank. After around 30 seconds, the address bar shows the OAuth2 redirect URI with the `code=` string, and the popup screen shows `504 Gateway Time-out` on the page.

**Expected behavior**

The OAuth2 credential should connect.

**Environment**

This is on Windows 8.1, with latest n8n 0.70.0 release, using Node 12.18.0. Tested both on git bash and PowerShell, both on Firefox and Chrome.

**Notes**

The fact that the `code=...` is successfully received, and then the POST request fails, seems to show that the OAuth2 flow is correctly configured.

Running `./packages/cli/bin/n8n start --tunnel` makes n8n use localtunnel. The URL is retrieved from `~/.n8n/config` or regenerated if `config` does not exist. I tried generating a new URL and connecting, but same result.

Running ngrok with `ngrok http 5678`, storing the ngrok address in an env var `export WEBHOOK_TUNNEL_URL='https://a073311a8a63.ngrok.io/'` and running `npm run start` makes n8n use the ngrok address. I accessed n8n at that ngrok address and tried connecting, but same result. The only difference is that it takes longer, about two minutes, for the `504 Gateway Time-out` error to occur.

**Comment by ivov** [comment]
Same behavior with Docker on Windows with MINGW64, when running n8n with `winpty docker run -it --rm --name n8n -p 5678:5678 n8nio/n8n`

**Comment by ivov** [comment]
Also failing with the new Gmail node:

![](https://cdn.discordapp.com/attachments/719550806780674050/725010144395657357/gmail-node-oauth2.gif)

**Comment by ivov** [comment]
Deactivating Windows Firewall and Windows Defender results in the same behavior.

**Comment by ivov** [comment]
Disabling HTTP2 in Firefox via `network.http.enabled.http2` in `about:config` results in the same behavior.

**Comment by ivov** [comment]
Removed everything, including the n8n global packages, and reinstalled everything from scratch and OAuth2 is working again. The origin of the issue is still unknown, but this is resolved now.
